export const GET_ALL_CATEGORIES = 'SAGA/GET_ALL_CATEGORIES';
export const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES';
export const GET_CATEGORY_DETAILS = 'SAGA/GET_CATEGORY_DETAILS';
export const SET_CATEGORY_DETAILS = 'SET_CATEGORY_DETAILS';